services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=chat
    ports:
      - "5432:5432"
    volumes:
      - ./src/data/init.sql:/docker-entrypoint-initdb.d/init.sql